kind: Deployment
apiVersion: apps/v1
metadata:
  name: toures-balon-usuario-categoria-deployment
  labels:
    app: toures-balon-usuario-categoria
spec:
  replicas: 2
  selector:
    matchLabels:
      app: toures-balon-usuario-categoria
  template:
    metadata:
      labels:
        app: toures-balon-usuario-categoria
    spec:
      containers:
        - name: toures-balon-usuario-categoria
          image: alejoab12/toures-balon-usuario-categoria
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "350Mi"
              cpu: "100m"
            limits:
              memory: "600Mi"
              cpu: "850m"